env:
    DIRECTORY: dist
    PROJECT_NAME: BedsteLectio

name: Release
on:
    workflow_dispatch: null
jobs:
    Version:
        outputs:
            created: ${{ env.DAILY_VERSION_CREATED }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 19.3.0
            - uses: pnpm/action-setup@v2
              with:
                  version: 8

            - name: Build
              run: |
                  pnpm install
                  pnpm upload
            - name: Create version and tag
              uses: fregante/daily-version-action@v2
            - name: Update manifest.json with version ${{ env.DAILY_VERSION}}
              if: env.DAILY_VERSION_CREATED
              run: |
                  pnpm dlx dot-json@1 "$DIRECTORY/firefox/manifest.json" version "$DAILY_VERSION"
                  pnpm dlx dot-json@1 "$DIRECTORY/chrome/manifest.json" version "$DAILY_VERSION"
                  pnpm dlx dot-json@1 "$DIRECTORY/edge/manifest.json" version "$DAILY_VERSION"

            - name: Upload Firefox Extension
              if: env.DAILY_VERSION_CREATED
              uses: actions/upload-artifact@v3
              with:
                  name: firefox
                  path: dist/firefox
            - name: Upload Chrome Extension
              if: env.DAILY_VERSION_CREATED
              uses: actions/upload-artifact@v3
              with:
                  name: chrome
                  path: dist/chrome
            - name: Upload Edge Extension
              if: env.DAILY_VERSION_CREATED
              uses: actions/upload-artifact@v3
              with:
                  name: edge
                  path: dist/edge

            - name: Create release
              if: env.DAILY_VERSION_CREATED
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              working-directory: ${{ env.DIRECTORY }}
              run: |
                  FILE_PREFIX="$PROJECT_NAME-$DAILY_VERSION"
                  cd firefox
                  zip -r "$FILE_PREFIX-firefox.zip" ./*
                  cd ../chrome
                  zip -r "$FILE_PREFIX-chrome.zip" ./*
                  cd ../edge
                  zip -r "$FILE_PREFIX-edge.zip" ./*
                  cd ..
                  gh release create "$DAILY_VERSION" --generate-notes "firefox/$FILE_PREFIX-firefox.zip" "chrome/$FILE_PREFIX-chrome.zip" "edge/$FILE_PREFIX-edge.zip"
